from __future__ import annotations

import logging
from datetime import datetime

import requests

from core.repo_manager import RepoManager
from models.job import JobState, JobStatus

logger = logging.getLogger(__name__)


def commit_node(state: JobState, repo_manager: RepoManager) -> dict:
    if not state.generated_files:
        return {
            "status": JobStatus.FAILED,
            "updated_at": datetime.utcnow(),
            "error_logs": state.error_logs + ["commit_node: no generated files to commit"],
        }

    repo_name = state.repo_name or f"skillnet-{state.story_id}"
    feature_id = state.story_content.get("feature_id", state.story_id)
    branch = f"feature/{feature_id}-{state.job_id[:8]}"
    commit_msg = f"feat({feature_id}): auto-generated implementation"

    try:
        if not state.repo_url:
            repo_url = repo_manager.create_repo(repo_name)
            logger.info("commit_node: created repo %s → %s", repo_name, repo_url)
        else:
            repo_url = state.repo_url

        repo_manager.create_branch(repo_name, branch)
        repo_manager.push_files(repo_name, branch, state.generated_files, commit_msg)

        analysis = state.story_content.get("analysis", {})
        summary = analysis.get("summary", "Auto-generated implementation.")
        pr_url = repo_manager.create_pr(
            repo=repo_name,
            branch=branch,
            title=f"[{feature_id}] {state.story_content.get('title', repo_name)}",
            body=f"{summary}\n\n---\n*Generated by Skillnet Pipeline (job `{state.job_id}`)*",
        )
        logger.info("commit_node job %s: PR created → %s", state.job_id, pr_url)

        last_commit_hash = _get_branch_sha(repo_manager, repo_name, branch)

    except requests.HTTPError as exc:
        logger.exception("commit_node HTTP error for job %s: %s", state.job_id, exc)
        return {
            "status": JobStatus.FAILED,
            "updated_at": datetime.utcnow(),
            "error_logs": state.error_logs + [f"commit_node HTTP error: {exc}"],
        }
    except Exception as exc:
        logger.exception("commit_node failed for job %s: %s", state.job_id, exc)
        return {
            "status": JobStatus.FAILED,
            "updated_at": datetime.utcnow(),
            "error_logs": state.error_logs + [f"commit_node error: {exc}"],
        }

    return {
        "repo_url": repo_url,
        "pr_url": pr_url,
        "last_commit_hash": last_commit_hash,
        "status": JobStatus.COMMITTED,
        "updated_at": datetime.utcnow(),
    }


def _get_branch_sha(repo_manager: RepoManager, repo: str, branch: str) -> str | None:
    try:
        resp = requests.get(
            f"{repo_manager._base}/repos/{repo_manager.owner}/{repo}/git/ref/heads/{branch}",
            headers=repo_manager._headers,
            timeout=15,
        )
        resp.raise_for_status()
        return str(resp.json()["object"]["sha"])
    except Exception:
        return None
